version: '3.8'
services:
  auth_service:
    build: ./auth_service
    ports:
      - '5001:5001'
    restart: always

  orders_service:
    build: ./orders_service
    ports:
      - '5002:5002'
    restart: always
    depends_on:
      - auth_service

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - orders_service